### ISSUE TITLE
Fix the "No user, no email, no password" feature

### ISSUE THREAD

**Issue by anagalacticRuby** [davidstevenrose/Find-A-Group#5]
If a user goes to the 'create account' screen and leaves all of the fields empty, they are currently still able to proceed back to the 'Login' screen.
After doing so, this user will be able to login with this recently created "empty fields" account.
Once the user arrives at the screen with all of the tabs relating to the major functions of this program, the user will be unable to join any groups. Trying to do so will result in a NullPointerException from Java, no matter what they do.

There should be some sort of validation check implemented at the create account screen that prevents users from creating accounts with empty fields as their password, username, and email address.

Suggestion: add in a few while loops to check if the fields .isEmpty() before taking the user back to the Login screen.

**Comment by brien17** [comment]
This bug should be fixed now. I added a check to see if all fields are completed before allowing the user to be taken back to the login screen.
