### ISSUE TITLE
Table Style Bug

### ISSUE THREAD

**Issue by davidstevenrose** [davidstevenrose/Find-A-Group#8]
![linemismatch](https://user-images.githubusercontent.com/33883868/68076281-0e133f00-fd89-11e9-99fb-3a3014d9e6ed.PNG)
If you look in the image above, the column lines between the table metadata and the rows are mismatched. Can this be fixed?

David.

**Comment by anagalacticRuby** [comment]
I'm sure that it could be fixed if someone were to fiddle with the css a bit more.

**Comment by anagalacticRuby** [comment]
This issue has been solved as of the most recent css update in master.
